version: '3'
services:
  web:
    build: .
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
      - ./docker/config/httpd/httpd:/etc/sysconfig/httpd
    ports:
      - "8220:80"
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "1184:80"
    links:
      - db
  migrate:
    build: .
    container_name: migrate
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER_NAME: devuser
      MYSQL_USER_PASS: devpass
      MYSQL_DB_NAME: test_db
    volumes:
      - ./migrations:/var/migrate/db/migrations
      - ./phinx.php:/var/www/html/phinx.php
    links:
     - db
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "9906:3306"
